# Generated by Django 6.1.1 on 2026-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_ta", models.CharField(blank=True, max_length=200)),
                ("summary_en", models.TextField()),
                ("summary_ta", models.TextField(blank=True)),
                ("body_en", models.TextField()),
                ("body_ta", models.TextField(blank=True)),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
